version: '3.9'

services:
  app:
    image: beer-front-app
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: taptrack
    ports:
      - "80:80"
    restart: always
    networks:
      - "my-network"

networks:
  my-network:
    name: network